### ISSUE TITLE
Attempting to write parquet file (using Pandas) fails on v0.8.0

### ISSUE THREAD

**Issue by tomerip** [dask/fastparquet#754]
```
df.to_parquet('./file/path.parquet', engine='fastparquet')
```

**What happened**:
Fails with `AttributeError: 'fastparquet.parquet_thrift' has no attribute 'SchemaElement'`

**What you expected to happen**:
Writes file without error.

**Anything else we need to know?**:
Simply downgrading v0.8.0 to v0.7.2 resolves the issue.

**Environment**:

- Dask version: none
- Python version: 3.6
- Operating System: ubuntu
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
It sounds like you make have trouble with multiple versions in your environment, or a failed update. The following lines work fine on fastparquet 0.8.0:
```
In [8]: import pandas as pd

In [9]: df = pd.DataFrame({"a": [1]})

In [10]: df.to_parquet("file.parq", engine="fastparquet")

In [11]: import fastparquet.parquet_thrift

In [12]: fastparquet.parquet_thrift.SchemaElement
Out[12]: functools.partial(<built-in function from_fields>, thrift_name='SchemaElement')
```

**Comment by tomerip** [comment]
Hi @martindurant 

Just created a new conda env with:
`conda create -n test_pq python=3.6`
Then after activating:
`pip install fastparquet`
(it installed v0.8.0)
Running this .py file:
```
import pandas as pd

df = pd.DataFrame([{"a": "0129023", "b": [{"c": {"d": 10}}]}])
# this is the format I'm actually trying to save

df.to_parquet("./file.parq", engine="fastparquet", index=False)
import fastparquet.parquet_thrift
print(fastparquet.parquet_thrift.SchemaElement)
```

If fails with:
```
python test.py                                                                127 err | test_pq py
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    df.to_parquet("./file.parq", engine="fastparquet", index=False)
  File "/Users/user/miniconda3/envs/test_pq/lib/python3.6/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/Users/user/miniconda3/envs/test_pq/lib/python3.6/site-packages/pandas/core/frame.py", line 2372, in to_parquet
    **kwargs,
  File "/Users/user/miniconda3/envs/test_pq/lib/python3.6/site-packages/pandas/io/parquet.py", line 276, in to_parquet
    **kwargs,
  File "/Users/user/miniconda3/envs/test_pq/lib/python3.6/site-packages/pandas/io/parquet.py", line 199, in write
    **kwargs,
  File "/Users/user/miniconda3/envs/test_pq/lib/python3.6/site-packages/fastparquet/writer.py", line 1209, in write
    partition_cols=partition_on)
  File "/Users/user/miniconda3/envs/test_pq/lib/python3.6/site-packages/fastparquet/writer.py", line 787, in make_metadata
    root = parquet_thrift.SchemaElement(name=b'schema',
AttributeError: module 'fastparquet.parquet_thrift' has no attribute 'SchemaElement'
```

However, if I'm doing the exact same thing only with `pip install fastparquet==0.7.2` it works perfectly.
By the way, this time I tried on macOS.

Also, if you take a look at this file:
https://github.com/dask/fastparquet/blob/0.8.0/fastparquet/parquet_thrift/parquet/ttypes.py

It doesn't contain the `SchemeElement` class, while the v0.7.2 one does (if I understand correctly, this file is actually the `parquet_thrift` module).

**Comment by martindurant** [comment]
Hm, actually SchemaElement is created [here](https://github.com/dask/fastparquet/blob/0.8.0/fastparquet/parquet_thrift/__init__.py#L5) - but I suppose this construct isn't functional in py3.6 . 3.7 works fine, and this didn't arise before, because conda only built fastparquet for 3.7+ . I could yank the 0.8.0/py36 files from pypi to prevent this happening to others, but you seem to be a rare one with that environment by now.

**Comment by tomerip** [comment]
So that for py3.6 the latest version will be v0.7.2 using pip? Sounds like a good solution.
I agree that py3.6 is pretty rare by now, I'm working with AWS SageMaker Studio and for some reason they didn't update the PyTorch containers to python 3.7 yet.
Anyway, thanks for the help! Should I close the issue?
